# Generated by Django 5.2.7 on 2026-04-11 03:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='AttributeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CourseLearningOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CourseObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberTheory', models.IntegerField()),
                ('numberPractice', models.IntegerField()),
                ('hourSelfStudy', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LearningMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MainSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('code', models.CharField(max_length=50)),
                ('position', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='ProgrammeLearningOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SubSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('position', models.IntegerField(default=1)),
                ('type', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=50)),
                ('main_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_sections', to='syllabuses.mainsection')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TemplateSyllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('structure', models.JSONField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TypeAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TypeLearningMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TypeRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_value', models.CharField(max_length=50)),
                ('attribute_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_values', to='syllabuses.attributegroup')),
            ],
        ),
        migrations.CreateModel(
            name='CloPloAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('clo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plo_association', to='syllabuses.courselearningoutcome')),
                ('plo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clo_association', to='syllabuses.programmelearningoutcome')),
            ],
        ),
        migrations.AddField(
            model_name='courselearningoutcome',
            name='course_objective',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_learning_outcomes', to='syllabuses.courseobjective'),
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('room', models.CharField(blank=True, max_length=200, null=True)),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lecturers', to='syllabuses.faculty')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('joined_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('avatar', models.CharField(blank=True, max_length=100, null=True)),
                ('user_role', models.IntegerField(choices=[('admin', 'Admin'), ('user', 'User'), ('specialist', 'Specialist')], default='user')),
                ('lecturer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='syllabuses.lecturer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='majors', to='syllabuses.faculty')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Method',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('time', models.TextField(blank=True, null=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_methods', to='syllabuses.assessment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MethodCourseLearningOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='syllabuses.courselearningoutcome')),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='syllabuses.method')),
            ],
        ),
        migrations.AddField(
            model_name='method',
            name='course_learning_outcomes',
            field=models.ManyToManyField(related_name='methods', through='syllabuses.MethodCourseLearningOutcome', to='syllabuses.courselearningoutcome'),
        ),
        migrations.CreateModel(
            name='CourseObjectiveProgrammeLearningOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_objective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='syllabuses.courseobjective')),
                ('programme_learning_outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='syllabuses.programmelearningoutcome')),
            ],
        ),
        migrations.AddField(
            model_name='courseobjective',
            name='programme_learning_outcomes',
            field=models.ManyToManyField(related_name='course_objectives', through='syllabuses.CourseObjectiveProgrammeLearningOutcome', to='syllabuses.programmelearningoutcome'),
        ),
        migrations.AddField(
            model_name='courselearningoutcome',
            name='plos',
            field=models.ManyToManyField(related_name='clos', through='syllabuses.CloPloAssociation', to='syllabuses.programmelearningoutcome'),
        ),
        migrations.CreateModel(
            name='ReferenceSubSection',
            fields=[
                ('subsection_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='syllabuses.subsection')),
                ('reference_code', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
            bases=('syllabuses.subsection',),
        ),
        migrations.CreateModel(
            name='SelectionSubSection',
            fields=[
                ('subsection_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='syllabuses.subsection')),
                ('attribute_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selection_sub_sections', to='syllabuses.attributegroup')),
            ],
            options={
                'abstract': False,
            },
            bases=('syllabuses.subsection',),
        ),
        migrations.CreateModel(
            name='TableSubSection',
            fields=[
                ('subsection_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='syllabuses.subsection')),
                ('data', models.JSONField()),
            ],
            options={
                'abstract': False,
            },
            bases=('syllabuses.subsection',),
        ),
        migrations.CreateModel(
            name='TextSubSection',
            fields=[
                ('subsection_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='syllabuses.subsection')),
                ('content', models.TextField(blank=True, null=True)),
                ('display_mode', models.CharField(default='input', max_length=50)),
                ('place_holder', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('syllabuses.subsection',),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('credit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subject', to='syllabuses.credit')),
            ],
        ),
        migrations.AddField(
            model_name='courseobjective',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_objectives', to='syllabuses.subject'),
        ),
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('structure_file', models.CharField(default='syllabus_2025.json', max_length=100)),
                ('start_date_edition', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date_edition', models.DateTimeField(default=django.utils.timezone.now)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syllabuses', to='syllabuses.faculty')),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syllabuses', to='syllabuses.lecturer')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syllabuses', to='syllabuses.subject')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='mainsection',
            name='syllabus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_sections', to='syllabuses.syllabus'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='syllabus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='syllabuses.syllabus'),
        ),
        migrations.CreateModel(
            name='SyllabusLearningMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learning_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='syllabuses.learningmaterial')),
                ('syllabus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='syllabuses.syllabus')),
            ],
        ),
        migrations.AddField(
            model_name='syllabus',
            name='learning_materials_rel',
            field=models.ManyToManyField(related_name='syllabuses_rel', through='syllabuses.SyllabusLearningMaterial', to='syllabuses.learningmaterial'),
        ),
        migrations.CreateModel(
            name='TeachingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_no', models.IntegerField()),
                ('content', models.TextField()),
                ('offline_activity', models.TextField(blank=True, null=True)),
                ('offline_hours', models.FloatField(default=0)),
                ('online_activity', models.TextField(blank=True, null=True)),
                ('online_hours', models.FloatField(default=0)),
                ('self_study_activity', models.TextField(blank=True, null=True)),
                ('self_study_hours', models.FloatField(default=0)),
                ('schedule_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_sessions', to='syllabuses.schedulegroup')),
                ('syllabus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_sessions', to='syllabuses.syllabus')),
            ],
            options={
                'ordering': ['session_no'],
            },
        ),
        migrations.CreateModel(
            name='TeachingSessionAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='syllabuses.assessment')),
                ('teaching_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='syllabuses.teachingsession')),
            ],
        ),
        migrations.AddField(
            model_name='teachingsession',
            name='assessments',
            field=models.ManyToManyField(through='syllabuses.TeachingSessionAssessment', to='syllabuses.assessment'),
        ),
        migrations.CreateModel(
            name='TeachingSessionCourseLearningOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='syllabuses.courselearningoutcome')),
                ('teaching_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='syllabuses.teachingsession')),
            ],
        ),
        migrations.AddField(
            model_name='teachingsession',
            name='course_learning_outcomes',
            field=models.ManyToManyField(through='syllabuses.TeachingSessionCourseLearningOutcome', to='syllabuses.courselearningoutcome'),
        ),
        migrations.CreateModel(
            name='TeachingSessionLearningMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learning_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='syllabuses.learningmaterial')),
                ('teaching_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='syllabuses.teachingsession')),
            ],
        ),
        migrations.AddField(
            model_name='teachingsession',
            name='learning_materials',
            field=models.ManyToManyField(through='syllabuses.TeachingSessionLearningMaterial', to='syllabuses.learningmaterial'),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syllabuses', to='syllabuses.templatesyllabus'),
        ),
        migrations.CreateModel(
            name='TrainingProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=150)),
                ('academic_year', models.IntegerField()),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_programs', to='syllabuses.major')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TrainingProgramSyllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('syllabus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='syllabuses.syllabus')),
                ('training_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='syllabuses.trainingprogram')),
            ],
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='syllabuses',
            field=models.ManyToManyField(related_name='training_programs', through='syllabuses.TrainingProgramSyllabus', to='syllabuses.syllabus'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='type_assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='syllabuses.typeassessment'),
        ),
        migrations.AddField(
            model_name='learningmaterial',
            name='type_material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_materials', to='syllabuses.typelearningmaterial'),
        ),
        migrations.CreateModel(
            name='RequirementSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('require_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_relation', to='syllabuses.subject')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_by_relation', to='syllabuses.subject')),
                ('type_requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirement_subjects', to='syllabuses.typerequirement')),
            ],
        ),
        migrations.CreateModel(
            name='SubSectionAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='syllabuses.attributevalue')),
                ('subsection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='syllabuses.selectionsubsection')),
            ],
        ),
        migrations.AddField(
            model_name='selectionsubsection',
            name='selected_values',
            field=models.ManyToManyField(through='syllabuses.SubSectionAttributeValue', to='syllabuses.attributevalue'),
        ),
        migrations.AddConstraint(
            model_name='mainsection',
            constraint=models.UniqueConstraint(fields=('code', 'syllabus'), name='uq_code_per_syllabus'),
        ),
    ]
