# Generated by Django 5.2.7 on 2026-07-07 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabuses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='syllabus',
            name='edit_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
