# Generated by Django 5.2.7 on 2026-07-26 03:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabuses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templatesyllabus',
            name='status',
        ),
        migrations.AddField(
            model_name='templatesyllabus',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='syllabuses.templatesyllabus'),
        ),
    ]
