# Generated by Django 5.2.7 on 2026-07-29 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabuses', '0002_remove_templatesyllabus_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseobjective',
            name='subject',
        ),
        migrations.AddField(
            model_name='courseobjective',
            name='syllabus',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='course_objectives', to='syllabuses.syllabus'),
            preserve_default=False,
        ),
    ]
