# Generated by Django 5.2.7 on 2026-07-08 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabuses', '0002_syllabus_edit_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatesyllabus',
            name='version',
            field=models.CharField(default='v1.0', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='templatesyllabus',
            unique_together={('name', 'version')},
        ),
        migrations.AddField(
            model_name='syllabus',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clones', to='syllabuses.syllabus'),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='version',
            field=models.CharField(default='v1.0', max_length=20),
        ),
        migrations.AddField(
            model_name='templatesyllabus',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='templatesyllabus',
            name='status',
            field=models.CharField(default='Draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='templatesyllabus',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='TemplateMainSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('code', models.CharField(max_length=50)),
                ('position', models.IntegerField(default=1)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_sections', to='syllabuses.templatesyllabus')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('template', 'code')},
            },
        ),
        migrations.CreateModel(
            name='TemplateSubSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=50)),
                ('position', models.IntegerField(default=1)),
                ('display_mode', models.CharField(blank=True, default='input', max_length=50, null=True)),
                ('place_holder', models.CharField(blank=True, max_length=100, null=True)),
                ('main_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_sections', to='syllabuses.templatemainsection')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.RemoveField(
            model_name='templatesyllabus',
            name='structure',
        ),
    ]
