# Generated by Django 5.2.7 on 2026-04-11 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabuses', '0003_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User'), ('specialist', 'Specialist')], default='user', max_length=20),
        ),
    ]
