# Generated by Django 5.2.7 on 2026-08-23 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabuses', '0004_subsection_requires_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textsubsection',
            name='display_mode',
            field=models.CharField(blank=True, default='input', max_length=50, null=True),
        ),
    ]
