# Generated by Django 5.2.7 on 2026-05-09 03:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabuses', '0004_alter_user_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='lecturer',
        ),
        migrations.AddField(
            model_name='lecturer',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='lecturer_profile', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
