# Generated by Django 5.2.7 on 2026-09-06 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabuses', '0005_alter_textsubsection_display_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='syllabus',
            name='revision',
            field=models.IntegerField(default=1),
        ),
    ]
