# Generated by Django 5.2.7 on 2026-06-07 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('syllabuses', '0005_remove_lecturer_email_remove_user_lecturer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturer',
            name='name',
        ),
    ]
