# Generated by Django 5.2.7 on 2026-06-15 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('syllabuses', '0006_remove_lecturer_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='credit',
            old_name='hourSelfStudy',
            new_name='hour_self_study',
        ),
        migrations.RenameField(
            model_name='credit',
            old_name='numberPractice',
            new_name='number_practice',
        ),
        migrations.RenameField(
            model_name='credit',
            old_name='numberTheory',
            new_name='number_theory',
        ),
    ]
