# Generated by Django 5.2.7 on 2026-09-11 09:02

import django.db.models.deletion
import django.utils.timezone
import syllabuses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabuses', '0006_syllabus_revision'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatesyllabus',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='templatesyllabus',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=syllabuses.models.template_upload_path, verbose_name='File mẫu DOCX'),
        ),
        migrations.AddField(
            model_name='templatesyllabus',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='TemplateControlField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(help_text='Tag đặt trong Word Content Control (ví dụ: SUBJECT_NAME)', max_length=100)),
                ('field_type', models.CharField(choices=[('TEXT', 'Văn bản đơn'), ('TABLE', 'Bảng dữ liệu lặp'), ('RICH_TEXT', 'Định dạng nâng cao')], default='TEXT', max_length=20)),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Mô tả trường')),
                ('is_locked', models.BooleanField(default=True, help_text='Khóa không cho sửa trong ONLYOFFICE')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='control_fields', to='syllabuses.templatesyllabus')),
            ],
            options={
                'db_table': 'template_control_field',
                'unique_together': {('template', 'tag')},
            },
        ),
    ]
