# Generated by Django 5.2.7 on 2026-09-11 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('syllabuses', '0007_templatesyllabus_created_at_templatesyllabus_file_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='templatecontrolfield',
            table=None,
        ),
    ]
