# Generated by Django 5.2.7 on 2026-06-16 03:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabuses', '0007_rename_hourselfstudy_credit_hour_self_study_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmelearningoutcome',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='programmelearningoutcome',
            name='name',
            field=models.CharField(default='PLO', max_length=100),
            preserve_default=False,
        ),
    ]
