# Generated by Django 5.2.7 on 2026-09-22 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabuses', '0008_alter_templatecontrolfield_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(help_text='Mã token, vd: SUBJECT_CODE, CUSTOM_TABLE_123', max_length=100, unique=True)),
                ('friendly_label', models.CharField(help_text='Tên tiếng Việt, vd: Mã môn học', max_length=255)),
                ('field_type', models.CharField(choices=[('SCALAR', 'Scalar (Giá trị đơn)'), ('TABLE_FIXED', 'Table Fixed (Bảng cố định)'), ('TABLE_DYNAMIC', 'Table Dynamic (Bảng động)')], default='SCALAR', max_length=20)),
                ('group', models.CharField(default='Thông tin chung', max_length=100)),
                ('schema', models.JSONField(blank=True, help_text='Lưu cấu trúc cột của bảng (chỉ dùng cho TABLE_DYNAMIC)', null=True)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='syllabuses.templatesyllabus')),
            ],
            options={
                'ordering': ['group', 'order'],
            },
        ),
        migrations.DeleteModel(
            name='TemplateControlField',
        ),
    ]
