# Generated by Django 5.2.7 on 2026-06-16 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabuses', '0008_programmelearningoutcome_created_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseobjective',
            options={'ordering': ['position']},
        ),
        migrations.AddField(
            model_name='courseobjective',
            name='position',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
