# Generated by Django 5.2.7 on 2026-06-16 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabuses', '0009_alter_courseobjective_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courselearningoutcome',
            name='position',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
