# Generated by Django 5.2.7 on 2026-06-21 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabuses', '0010_courselearningoutcome_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningmaterial',
            name='type_material',
        ),
        migrations.AddField(
            model_name='syllabuslearningmaterial',
            name='type_material',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='syllabuses.typelearningmaterial'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='learningmaterial',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='syllabuslearningmaterial',
            unique_together={('syllabus', 'learning_material')},
        ),
    ]
